services:
  locationaccess:
    image: locationaccess
    restart: always
    build:
      context: .
      dockerfile: LocationAccess/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ORLEAN_UseRedis: true
      UseRedis: true
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cache
    volumes:
      - sqlite_files:/app/sqlite
  locationaccessscale:
    image: locationaccess
    scale: 2
    restart: always
    build:
      context: .
      dockerfile: LocationAccess/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ORLEAN_UseRedis: true
      UseRedis: true
    depends_on:
      - cache 
    volumes:
      - sqlite_files:/app/sqlite
  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:cache:6379
    ports:
      - "8081:8081"
    depends_on:
      - cache
      
volumes:
  sqlite_files: